version: '3.8'

services:
    loadgenerator:
        #image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.1
        build: ../src/loadgenerator
        network_mode: host
        environment:
            - FRONTEND_ADDR=${FRONTEND_ENDPOINT:-http://127.0.0.1:80}
            - USERS=10
