version: '3.8'

services:
    # currencyservice-fgx2efhqra-ey.a.run.app:443
    currencyservice:
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.1
        container_name: boutique-currency
        environment:
            PORT: 7000
            DISABLE_PROFILER: 0

    # productcatalogservice-fgx2efhqra-ey.a.run.app:443
    productcatalogservice:
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
        container_name: boutique-product
        environment:
            PORT: 3550
            DISABLE_PROFILER: 1

    checkoutservice:
        #image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.1
        build: ../src/checkout
        container_name: boutique-checkout
        environment:
            PORT: 5050
            PRODUCT_CATALOG_SERVICE_ADDR: grpc://productcatalogservice:3550
            SHIPPING_SERVICE_ADDR: grpc://shippingservice:50051
            PAYMENT_SERVICE_ADDR: grpc://paymentservice:50051
            EMAIL_SERVICE_ADDR: grpc://emailservice:8080
            CURRENCY_SERVICE_ADDR: grpc://currencyservice:7000
            CART_SERVICE_ADDR: grpc://cartservice:7070
            OPTIONAL_PAYMENT_FEATURE: 1
            PREMIUM_PAYMENT_FEATURE: 0

    shippingservice:
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.1
        container_name: boutique-shipping
        environment:
            PORT: 50051
            DISABLE_PROFILER: 1

    cartservice:
        #image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.1
        build: ../src/cart/src
        container_name: boutique-cart
        environment:
            #REDIS_ADDR: redis-cart:6379
            MYSQL_HOST: cartservice-store
            MYSQL_PORT: 3306
            MYSQL_DATABASE: cart
            MYSQL_USER: cart
            MYSQL_PASSWORD: password
            MYSQL_TABLE: carts
            MYSQL_SSL_MODE: None

    #redis-cart-store:
    #    image: redis:alpine
    #    volumes:
    #        - redis-data:/data

    cartservice-store:
        image: mysql:5.7
        container_name: boutique-cart-store
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cart
            MYSQL_USER: cart
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data:/var/lib/mysql

    emailservice:
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
        container_name: boutique-email
        environment:
            PORT: 8080
            DISABLE_PROFILER: 1

    paymentservice:
        #image: gcr.io/google-samples/microservices-demo/paymentservice:v0.10.1
        build: ../src/payment
        container_name: boutique-payment
        environment:
            PORT: 50051
            OPTIONAL_PAYMENT_FEATURE: 1
            PREMIUM_PAYMENT_FEATURE: 0
            DISABLE_PROFILER: 1

    frontend:
        #image: gcr.io/google-samples/microservices-demo/frontend:v0.10.1
        build: ../src/frontend
        container_name: boutique-frontend
        ports:
            - '80:8080'
        environment:
            PORT: 8080
            PRODUCT_CATALOG_SERVICE_ADDR: grpc://productcatalogservice:3550
            CURRENCY_SERVICE_ADDR: grpc://currencyservice:7000
            CART_SERVICE_ADDR: grpc://cartservice:7070
            RECOMMENDATION_SERVICE_ADDR: grpc://recommendationservice:8080
            SHIPPING_SERVICE_ADDR: grpc://shippingservice:50051
            CHECKOUT_SERVICE_ADDR: grpc://checkoutservice:5050
            AD_SERVICE_ADDR: grpc://adservice:9555
            SHOPPING_ASSISTANT_SERVICE_ADDR: 'required-some-dummy'
            DISABLE_PROFILER: 1
            OPTIONAL_PAYMENT_FEATURE: 1
            PREMIUM_PAYMENT_FEATURE: 0

    recommendationservice:
        #image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.1
        build: ../src/recommendation
        container_name: boutique-recommendation
        environment:
            PORT: 8080
            PRODUCT_CATALOG_SERVICE_ADDR: grpc://productcatalogservice:3550
            DISABLE_PROFILER: 1

    adservice:
        image: gcr.io/google-samples/microservices-demo/adservice:v0.10.1
        container_name: boutique-advertisement
        environment:
            PORT: 9555

    analyticsservice:
        build: ../src/analytics
        container_name: boutique-analytics
        environment:
            PORT: 9555
            CHECKOUT_SERVICE_ADDR: grpc://checkoutservice:5050
            RECOMMENDATION_SERVICE_ADDR: grpc://recommendationservice:8080
            DISABLE_PROFILER: 1

volumes:
    #redis-data:
    mysql-data:
